services:
  accountsdb:
    image: mysql:latest
    container_name: accountsdb
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - vigneshbank

  loansdb:
    image: mysql:latest
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - vigneshbank

  cardsdb:
    image: mysql:latest
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - vigneshbank

  configserver:
    image: "vigneshramnalla/configserver:s7"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/Vigneshnalla/microservices-config.git
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
      SPRING_PROFILES_ACTIVE: git
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - vigneshbank

  accounts:
    image: "vigneshramnalla/accounts:s7"
    container_name: "accounts"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8071/'

      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - vigneshbank

  loans:
    image: "vigneshramnalla/loans:s7"
    container_name: "loans"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - vigneshbank

  cards:
    image: "vigneshramnalla/cards:s7"
    container_name: "cards"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - vigneshbank

networks:
  vigneshbank:
    driver: "bridge"
