services:
  network-deploy-service:
    networks:
      - vigneshbank

  microservice-base-config:
    extends:
      service: network-deploy-service
   

  microservice-configserver-config:
    extends:
      service: microservice-base-config


