services:
  rabbit:
    image: "rabbitmq:3.12-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    
    networks:
      - vigneshbank

  configserver:
    image: "vigneshramnalla/configserver:s6"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
    extends:
      file: common-config.yml
      service: microservice-base-config
    networks:
      - vigneshbank

  accounts:
    image: "vigneshramnalla/accounts:s6"
    container_name: "accounts"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

    depends_on:
      configserver:
        condition: service_healthy

    networks:
      - vigneshbank

  loans:
    image: "vigneshramnalla/loans:s6"
    container_name: "loans"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

    depends_on:
      configserver:
        condition: service_healthy


    networks:
      - vigneshbank

  cards:
    image: "vigneshramnalla/cards:s6"
    container_name: "cards"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

    depends_on:
      configserver:
        condition: service_healthy

    networks:
      - vigneshbank

# Network definition
networks:
  vigneshbank:
    driver: "bridge"
