server:
  port: 9000
spring:
  application:
    name: "accounts"
  profiles:
    active: qa
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://localhost:8071/" #config server url for fetching the config

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
